import Head from "next/head";

export const Home = () => {
  return (
    <>
      <Head>
        <title>HOMEPAGE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`bg-gray-50`}>
        <div className={`flex h-screen flex-col items-center justify-center`}>
          <h1 className={`text-3xl font-bold text-gray-900`}>HOMEPAGE</h1>
        </div>
      </div>
    </>
  );
};

export default Home;
